### ISSUE TITLE
Update package to be compatible with go1.12

### ISSUE THREAD

**Issue by mfridman** [elliotforbes/go-webassembly-framework#2]
There have been a few breaking changes recently that'll eventually land in go1.12. Are there any plans to update this package?

https://tip.golang.org/doc/go1.12#syscall/js

**Comment by elliotforbes** [comment]
Thanks for the heads up!

I'll take a look and create a `1.12` branch which will contain the necessary changes for the release in February!

**Comment by elliotforbes** [comment]
This can be closed as the framework has been updated to work with Go 1.15 and Tinygo
